// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetRoot implements getRoot operation.
//
// GET /
func (UnimplementedHandler) GetRoot(ctx context.Context) error {
	return ht.ErrNotImplemented
}

// GetWallpaper implements getWallpaper operation.
//
// Returns a wallpaper with the given ID.
//
// GET /wallpapers/{id}
func (UnimplementedHandler) GetWallpaper(ctx context.Context, params GetWallpaperParams) (r GetWallpaperRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWallpaperTags implements getWallpaperTags operation.
//
// Returns a list of tags.
//
// GET /wallpapers/tags
func (UnimplementedHandler) GetWallpaperTags(ctx context.Context) (r GetWallpaperTagsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWallpapers implements getWallpapers operation.
//
// Returns a list of wallpapers.
//
// GET /wallpapers
func (UnimplementedHandler) GetWallpapers(ctx context.Context, params GetWallpapersParams) (r GetWallpapersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWallpapersByTag implements getWallpapersByTag operation.
//
// Returns a list of wallpapers with the given tag.
//
// GET /wallpapers/tags/{tag}
func (UnimplementedHandler) GetWallpapersByTag(ctx context.Context, params GetWallpapersByTagParams) (r GetWallpapersByTagRes, _ error) {
	return r, ht.ErrNotImplemented
}
