// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetRootOperation            OperationName = "GetRoot"
	GetWallpaperOperation       OperationName = "GetWallpaper"
	GetWallpaperTagsOperation   OperationName = "GetWallpaperTags"
	GetWallpapersOperation      OperationName = "GetWallpapers"
	GetWallpapersByTagOperation OperationName = "GetWallpapersByTag"
)
