// Code generated by ogen, DO NOT EDIT.
package api

type GetWallpaperRes interface {
	getWallpaperRes()
}

type GetWallpaperTagsRes interface {
	getWallpaperTagsRes()
}

type GetWallpapersByTagRes interface {
	getWallpapersByTagRes()
}

type GetWallpapersRes interface {
	getWallpapersRes()
}
